"""Published fingerprints of the sealed scrolls.

Generated by seal_scrolls.py. Do not edit by hand: a fingerprint that does not
match its scroll stops the server serving that scroll. The texts themselves
are kept off this repository; see cultivation.py.
"""

STATUS = "draft"
SEALED_ON = None

FINGERPRINTS = {
    "first-pass": "c6fc5268775f52c1fd7fb81366cf5f858a322bb6ee8770de67b334238f48224b",
    "middle-pass": "19696238a815749ddb03ce69c9092b55898e415b1b9182fb31b22556eec20de5",
    "three-years": "22dadeb07b6ee1a12d6e2cf0d0783254f6db4b1f28fb466d7468ccf402407f87",
    "upper-pass": "7556b029f1d6101df11fb52e51e8717de0bf7409161f023c89f639d8dabee2e6",
}
