"""Seal the later scrolls: fingerprint their text and publish only the fingerprints.

    python seal_scrolls.py /path/to/sealed-scrolls.json           # draft fingerprints
    python seal_scrolls.py /path/to/sealed-scrolls.json --final   # the real seal

Reads the private scroll file, gives any scroll without a nonce a fresh random
one (writing the file back), and rewrites scroll_commitments.py with the
SHA-256 fingerprint of each scroll. Commit scroll_commitments.py. Never commit
the scroll file: this repository is public, and the texts are only on the
server.

Without --final the fingerprints are marked as drafts, which is what they are
until the texts have been read and approved. --final refuses any scroll that
still contains a "[DRAFT" marker and records the date. From then on a scroll
can only change by publishing a new fingerprint, in the open. To anchor that
date somewhere nobody controls, timestamp the committed file on Bitcoin with
OpenTimestamps (`ots stamp scroll_commitments.py`) and commit the .ots proof.

Anyone can verify an opened scroll: the app shows its key, title, text and
nonce, and SHA-256 over those fields (see cultivation.fingerprint) must equal
the fingerprint published here.
"""

import argparse
import json
import secrets
import sys
from datetime import date
from pathlib import Path

from cultivation import PASSES, fingerprint

HERE = Path(__file__).resolve().parent
TARGET = HERE / "scroll_commitments.py"

HEADER = '''"""Published fingerprints of the sealed scrolls.

Generated by seal_scrolls.py. Do not edit by hand: a fingerprint that does not
match its scroll stops the server serving that scroll. The texts themselves
are kept off this repository; see cultivation.py.
"""
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("scrolls", type=Path, help="the private sealed-scrolls JSON file")
    parser.add_argument("--final", action="store_true", help="seal for real: refuse drafts and record the date")
    args = parser.parse_args()

    data = json.loads(args.scrolls.read_text(encoding="utf-8"))
    sealed_keys = {p["key"]: p for p in PASSES if p.get("sealed")}
    scrolls = data.get("scrolls", [])

    problems = []
    seen = set()
    for s in scrolls:
        key = s.get("key")
        if key not in sealed_keys:
            problems.append(f"{key!r} is not a sealed pass")
            continue
        seen.add(key)
        if s.get("title") != sealed_keys[key]["title"]:
            problems.append(f"{key}: title {s.get('title')!r} differs from the app's {sealed_keys[key]['title']!r}")
        if not str(s.get("body", "")).strip():
            problems.append(f"{key}: empty body")
        if args.final and "[DRAFT" in json.dumps(s, ensure_ascii=False):
            problems.append(f"{key}: still marked [DRAFT")
    missing = set(sealed_keys) - seen
    if missing:
        problems.append(f"missing scrolls: {', '.join(sorted(missing))}")
    if problems:
        print("Not sealed:\n  " + "\n  ".join(problems), file=sys.stderr)
        return 1

    changed = False
    for s in scrolls:
        if not s.get("nonce"):
            s["nonce"] = secrets.token_hex(16)
            changed = True
    if changed:
        args.scrolls.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    prints = {s["key"]: fingerprint(s) for s in sorted(scrolls, key=lambda s: sealed_keys[s["key"]]["day"])}
    status = "sealed" if args.final else "draft"
    sealed_on = repr(date.today().isoformat()) if args.final else "None"
    lines = [HEADER, f'STATUS = "{status}"', f"SEALED_ON = {sealed_on}", "", "FINGERPRINTS = {"]
    lines += [f'    "{k}": "{v}",' for k, v in prints.items()]
    lines += ["}", ""]
    TARGET.write_text("\n".join(lines), encoding="utf-8")

    for k, v in prints.items():
        print(f"{k:12} {v}")
    print(f"Wrote {TARGET.name} ({status}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
