"""Curated seed content for the Immortality — Dao Longevity app.

Content is sourced from publicly documented traditions (Ba Duan Jin, Zhan Zhuang,
Yangsheng principles, Ayurvedic Dinacharya). Framed strictly as historical
practices and personal exploration — never as medical advice.
"""

# ---------------------------------------------------------------------------
# PRACTICE LIBRARY (Dao + Ayurveda)
# ---------------------------------------------------------------------------

PRACTICES = [
    # ---------------- DAO ----------------
    {
        "practice_id": "daoyin",
        "title": "Daoyin — Guided Stretching",
        "tradition": "dao",
        "category": "Movement",
        "difficulty": "beginner",
        "time_min": 15,
        "origin_text": "Daoyin Tu (Han Dynasty silk illustrations, ~168 BCE)",
        "historical_context": "Daoyin (\u5c0e\u5f15, 'guiding and pulling') are among the oldest recorded stretching sequences, painted on silk unearthed at Mawangdui. Early Daoists used them to 'guide the qi and stretch the body' as a foundation for longer cultivation.",
        "modern_understanding": "Gentle mobility work that warms joints, lengthens fascia and settles the nervous system before deeper practice.",
        "instructions": [
            "Stand tall, feet shoulder-width, knees soft.",
            "Slowly roll the neck, then the shoulders, feeling each joint open.",
            "Fold gently from the hips, letting the spine unspool bone by bone.",
            "Move without forcing — let the breath lead each stretch.",
            "Finish standing still, hands resting on the lower belly.",
        ],
        "safety_note": "Never stretch into sharp pain — ease is the goal, not range.",
    },
    {
        "practice_id": "ba-duan-jin",
        "title": "Ba Duan Jin — Eight Brocades",
        "tradition": "dao",
        "category": "Qi Gong",
        "difficulty": "beginner",
        "time_min": 20,
        "origin_text": "Attributed to General Yue Fei (Song Dynasty, ~1150 CE)",
        "historical_context": "The 'Eight Pieces of Brocade' is one of the most widely practised qigong sets in China, traditionally used to keep soldiers and scholars healthy through eight flowing movements.",
        "modern_understanding": "A low-impact routine linking breath to movement, supporting posture, balance and circulation.",
        "instructions": [
            "Warm up with a few natural breaths, feet shoulder-width.",
            "Move through the eight forms slowly, one breath per movement.",
            "\u2018Two hands hold up the heavens\u2019 to begin — reach and lengthen.",
            "Keep knees soft and shoulders relaxed throughout.",
            "Return to stillness and feel the body settle.",
        ],
        "safety_note": None,
    },
    {
        "practice_id": "wu-qin-xi",
        "title": "Wu Qin Xi — Five Animal Frolics",
        "tradition": "dao",
        "category": "Qi Gong",
        "difficulty": "beginner",
        "time_min": 20,
        "origin_text": "Attributed to physician Hua Tuo (Eastern Han, ~200 CE)",
        "historical_context": "Hua Tuo observed the tiger, deer, bear, monkey and crane, shaping their movements into an exercise 'to make the body light and the appetite good.'",
        "modern_understanding": "Playful, expressive movement that mobilises the whole body and lifts mood.",
        "instructions": [
            "Choose one animal to explore each day.",
            "Tiger: strong, grounded reaching. Deer: light, turning steps.",
            "Bear: heavy, rolling sways. Monkey: quick, curious reaches.",
            "Crane: slow, balanced openings of the arms.",
            "Let the movement be a little playful — this is a frolic, not a drill.",
        ],
        "safety_note": None,
    },
    {
        "practice_id": "shun-hu-xi",
        "title": "Shun Hu Xi — Natural Breathing",
        "tradition": "dao",
        "category": "Breathwork",
        "difficulty": "beginner",
        "time_min": 10,
        "origin_text": "Classical Daoist breath cultivation (tu na)",
        "historical_context": "Before any advanced method, Daoists returned to 'natural breathing' — simply noticing and un-forcing the breath the body already knows.",
        "modern_understanding": "Restoring quiet nasal breathing that down-regulates the stress response.",
        "instructions": [
            "Sit comfortably, spine tall but not stiff.",
            "Breathe only through the nose.",
            "Do nothing to the breath — only watch it come and go.",
            "Notice where it moves: chest, ribs, belly.",
            "Rest here for ten minutes, returning whenever the mind drifts.",
        ],
        "safety_note": None,
    },
    {
        "practice_id": "abdominal-breathing",
        "title": "Fu Shi Hu Xi — Abdominal Breathing",
        "tradition": "dao",
        "category": "Breathwork",
        "difficulty": "beginner",
        "time_min": 12,
        "origin_text": "Daoist tu na (\u5410\u7d0d) breathing methods",
        "historical_context": "Sinking the breath to the lower belly (dantian) is a cornerstone of Daoist practice, said to 'root' the qi and calm the spirit.",
        "modern_understanding": "Diaphragmatic breathing that improves oxygen exchange and vagal tone.",
        "instructions": [
            "Rest one hand on the lower belly.",
            "Inhale softly, letting the belly gently expand into the hand.",
            "Exhale, letting the belly fall — no straining.",
            "Keep the chest quiet; the movement is low and small.",
            "Continue for ten to twelve minutes.",
        ],
        "safety_note": "If you feel dizzy, return to normal breathing and rest.",
    },
    {
        "practice_id": "long-breath",
        "title": "The Long Breath Method",
        "tradition": "dao",
        "category": "Breathwork",
        "difficulty": "intermediate",
        "time_min": 15,
        "origin_text": "Daoist 'long breath' (chang xi) cultivation",
        "historical_context": "Later stages of Daoist breathing gradually lengthen and refine the breath until it becomes 'so fine a feather would not stir.'",
        "modern_understanding": "Slow, extended breathing that trains respiratory control and deep calm.",
        "instructions": [
            "Begin from settled abdominal breathing.",
            "Gently lengthen the exhale, then the inhale — never to strain.",
            "Aim for smooth, silent, even breaths.",
            "If the breath jerks or you gasp, shorten it again.",
            "Let length arrive on its own over weeks, not by force.",
        ],
        "safety_note": "If you have respiratory or cardiovascular conditions, check with your doctor before practising breath lengthening.",
    },
    {
        "practice_id": "zhan-zhuang",
        "title": "Zhan Zhuang — Standing Meditation",
        "tradition": "dao",
        "category": "Standing",
        "difficulty": "intermediate",
        "time_min": 15,
        "origin_text": "Classical internal-arts 'standing post' practice",
        "historical_context": "\u2018Standing like a post\u2019 is a foundational internal exercise, used across Daoist and martial traditions to build structural alignment and rooted stillness.",
        "modern_understanding": "Isometric postural training that develops stability, patience and body awareness.",
        "instructions": [
            "Stand feet shoulder-width, knees slightly bent.",
            "Round the arms as if holding a large, light ball at chest height.",
            "Soften the shoulders, lengthen the crown upward.",
            "Breathe naturally and simply remain.",
            "Start with a few minutes and grow slowly over weeks.",
        ],
        "safety_note": "Come down gently if the legs shake strongly or you feel faint.",
    },
    {
        "practice_id": "jinggong",
        "title": "Jinggong — Seated Stillness",
        "tradition": "dao",
        "category": "Meditation",
        "difficulty": "beginner",
        "time_min": 15,
        "origin_text": "Daoist 'quiet sitting' (jing zuo)",
        "historical_context": "Quiet sitting was practised by Daoist and Confucian scholars alike as a way to still the mind and 'return to the root.'",
        "modern_understanding": "Seated meditation that trains attention and reduces mental restlessness.",
        "instructions": [
            "Sit on a cushion or chair, spine self-supporting.",
            "Let the hands rest in the lap, eyes soft or lightly closed.",
            "Follow the breath at the lower belly.",
            "When thoughts arise, note them and return — again and again.",
            "End by rubbing the hands and gently opening the eyes.",
        ],
        "safety_note": None,
    },
    {
        "practice_id": "yangsheng-diet",
        "title": "Yangsheng Dietary Principles",
        "tradition": "dao",
        "category": "Life Nourishing",
        "difficulty": "beginner",
        "time_min": 0,
        "origin_text": "Yangsheng (\u990a\u751f, 'nourishing life') tradition",
        "historical_context": "Daoist yangsheng teaches eating for harmony: warm, simple, seasonal food, eaten with calm attention and stopping before fullness.",
        "modern_understanding": "Mindful, moderate eating habits that support digestion and steady energy.",
        "instructions": [
            "Favour warm, cooked, simple meals.",
            "Eat slowly and with attention, without screens.",
            "Stop at around 70% full.",
            "Let the largest meal fall in the middle of the day.",
            "Notice how different foods leave you feeling.",
        ],
        "safety_note": "These are general traditional principles, not a diet plan — consult a professional for medical dietary needs.",
    },
    {
        "practice_id": "sleep-hygiene",
        "title": "Daoist Sleep Rhythm",
        "tradition": "dao",
        "category": "Life Nourishing",
        "difficulty": "beginner",
        "time_min": 0,
        "origin_text": "Yangsheng seasonal & daily rhythms",
        "historical_context": "Classical texts advise sleeping and rising with the light, resting the liver before midnight and letting the body follow the day.",
        "modern_understanding": "Consistent sleep-wake timing that supports circadian health.",
        "instructions": [
            "Aim to be asleep before 11pm where possible.",
            "Dim lights and screens as the evening settles.",
            "Keep a regular rising time, even after a poor night.",
            "Let the last hour before bed be quiet.",
            "Rise gently and greet daylight early.",
        ],
        "safety_note": None,
    },
    {
        "practice_id": "seasonal-living",
        "title": "Seasonal Living — Four Seasons",
        "tradition": "dao",
        "category": "Life Nourishing",
        "difficulty": "beginner",
        "time_min": 0,
        "origin_text": "Huangdi Neijing, 'Four Seasons' chapter",
        "historical_context": "The Neijing describes living in accord with the seasons: expanding in spring and summer, gathering inward in autumn and winter.",
        "modern_understanding": "Adjusting activity, rest and food to the season to reduce strain.",
        "instructions": [
            "Spring: rise earlier, move more, begin new things.",
            "Summer: stay active, let the body sweat lightly.",
            "Autumn: begin to gather in, tidy commitments.",
            "Winter: rest more, conserve, keep warm.",
            "Notice one seasonal shift you can honour this week.",
        ],
        "safety_note": None,
    },
    {
        "practice_id": "jing-conservation",
        "title": "Jing — Essence Conservation",
        "tradition": "dao",
        "category": "Life Nourishing",
        "difficulty": "intermediate",
        "time_min": 0,
        "origin_text": "Daoist Three Treasures (Jing, Qi, Shen)",
        "historical_context": "Daoists regard Jing (essence) as a finite root of vitality, to be conserved through moderation rather than spent recklessly.",
        "modern_understanding": "A traditional framing of avoiding chronic depletion — rest, moderation and recovery.",
        "instructions": [
            "Notice where you routinely over-spend energy.",
            "Protect recovery: sleep, stillness, quiet.",
            "Practise moderation in stimulation and excess.",
            "Balance effort with genuine rest.",
            "Treat energy as something to steward, not burn.",
        ],
        "safety_note": None,
    },
    # ---------------- AYURVEDA ----------------
    {
        "practice_id": "dinacharya",
        "title": "Dinacharya — Daily Routine",
        "tradition": "ayurveda",
        "category": "Daily Rhythm",
        "difficulty": "beginner",
        "time_min": 0,
        "origin_text": "Ashtanga Hridayam & classical Ayurvedic texts",
        "historical_context": "Dinacharya lays out an ideal daily rhythm — waking before sunrise, cleansing, movement and meals at regular times — to keep the doshas balanced.",
        "modern_understanding": "A structured daily routine supporting circadian rhythm and digestion.",
        "instructions": [
            "Wake close to sunrise where you can.",
            "Cleanse: mouth, tongue, face, senses.",
            "Drink warm water to gently wake digestion.",
            "Move the body, then settle for a calm breakfast.",
            "Keep meals and sleep at consistent times.",
        ],
        "safety_note": None,
    },
    {
        "practice_id": "tongue-scraping",
        "title": "Jihwa Prakshalana — Tongue Scraping",
        "tradition": "ayurveda",
        "category": "Cleansing",
        "difficulty": "beginner",
        "time_min": 2,
        "origin_text": "Classical Ayurvedic morning hygiene",
        "historical_context": "Scraping the tongue on waking is a traditional part of Dinacharya, said to remove 'ama' (residue) and awaken the senses.",
        "modern_understanding": "A simple oral-hygiene habit that freshens the mouth.",
        "instructions": [
            "On waking, before drinking, take a tongue scraper.",
            "Gently draw it from back to front a few times.",
            "Rinse the scraper between strokes.",
            "Follow with warm water.",
            "Notice the taste and freshness afterwards.",
        ],
        "safety_note": None,
    },
    {
        "practice_id": "abhyanga",
        "title": "Abhyanga — Self Oil Massage",
        "tradition": "ayurveda",
        "category": "Self Care",
        "difficulty": "beginner",
        "time_min": 15,
        "origin_text": "Charaka Samhita & Ashtanga Hridayam",
        "historical_context": "Daily self-massage with warm oil is praised in the classics as nourishing to the skin, calming to the nerves and grounding for Vata.",
        "modern_understanding": "A soothing self-care ritual that relaxes the body before bathing.",
        "instructions": [
            "Warm a little oil (sesame is traditional).",
            "Massage from the extremities toward the heart.",
            "Use circular strokes on joints, long strokes on limbs.",
            "Spend a moment on the feet and scalp.",
            "Let it soak in, then bathe in warm water.",
        ],
        "safety_note": "Patch-test new oils; avoid over broken or irritated skin.",
    },
    {
        "practice_id": "nadi-shodhana",
        "title": "Nadi Shodhana — Alternate Nostril Breath",
        "tradition": "ayurveda",
        "category": "Pranayama",
        "difficulty": "beginner",
        "time_min": 10,
        "origin_text": "Hatha Yoga Pradipika & Ayurvedic pranayama",
        "historical_context": "'Channel-cleansing breath' alternates the nostrils to balance the flow of prana and quiet the mind before meditation.",
        "modern_understanding": "A balancing breath practice that supports focus and calm.",
        "instructions": [
            "Sit comfortably, spine tall.",
            "Close the right nostril, inhale gently through the left.",
            "Close the left, exhale through the right.",
            "Inhale right, then switch and exhale left.",
            "Continue slowly, keeping the breath smooth and quiet.",
        ],
        "safety_note": "Keep the breath easy; if you have respiratory conditions, check with your doctor first.",
    },
    {
        "practice_id": "ujjayi",
        "title": "Ujjayi — Ocean Breath",
        "tradition": "ayurveda",
        "category": "Pranayama",
        "difficulty": "beginner",
        "time_min": 10,
        "origin_text": "Hatha Yoga Pradipika",
        "historical_context": "'Victorious breath' gently narrows the throat to create a soft ocean-like sound, traditionally used to steady the mind.",
        "modern_understanding": "A slow, audible breath that lengthens exhalation and calms the system.",
        "instructions": [
            "Breathe through the nose with a slight throat constriction.",
            "Let a soft ocean-like sound arise on each breath.",
            "Keep inhale and exhale even and unhurried.",
            "Relax the face and jaw.",
            "Continue for several soft, steady minutes.",
        ],
        "safety_note": None,
    },
    {
        "practice_id": "dosha-awareness",
        "title": "Dosha Awareness",
        "tradition": "ayurveda",
        "category": "Knowledge",
        "difficulty": "beginner",
        "time_min": 0,
        "origin_text": "Ayurvedic theory of the three doshas",
        "historical_context": "Ayurveda describes three functional energies — Vata (movement), Pitta (transformation) and Kapha (structure) — whose balance shapes body and temperament.",
        "modern_understanding": "A reflective framework for noticing your own tendencies and needs.",
        "instructions": [
            "Read the qualities of Vata, Pitta and Kapha.",
            "Notice which patterns feel most like you.",
            "Observe how they shift with season and stress.",
            "Use it as gentle self-inquiry, not a fixed label.",
            "Let awareness guide small daily choices.",
        ],
        "safety_note": None,
    },
    {
        "practice_id": "ritucharya",
        "title": "Ritucharya — Seasonal Eating",
        "tradition": "ayurveda",
        "category": "Daily Rhythm",
        "difficulty": "beginner",
        "time_min": 0,
        "origin_text": "Classical Ayurvedic seasonal regimen",
        "historical_context": "Ritucharya guides adjusting food and routine to each season to keep the doshas in balance across the year.",
        "modern_understanding": "Eating seasonally and adjusting habits to weather and climate.",
        "instructions": [
            "Favour warming, moist foods in cold, dry seasons.",
            "Favour cooling, light foods in heat.",
            "Eat fresh, local, seasonal produce where possible.",
            "Adjust spice and portion to the weather.",
            "Notice how the season changes your appetite.",
        ],
        "safety_note": None,
    },
    {
        "practice_id": "warm-water",
        "title": "Ushnodaka — Warm Water Habit",
        "tradition": "ayurveda",
        "category": "Daily Rhythm",
        "difficulty": "beginner",
        "time_min": 2,
        "origin_text": "Ayurvedic digestive practices",
        "historical_context": "Sipping warm water, especially in the morning, is a classic Ayurvedic habit to kindle 'agni', the digestive fire.",
        "modern_understanding": "A gentle hydration habit some find soothing for digestion.",
        "instructions": [
            "On waking, sip a cup of warm (not hot) water.",
            "Drink slowly, seated, with attention.",
            "Favour warm drinks over iced through the day.",
            "Sip rather than gulp with meals.",
            "Notice the effect on how you feel after eating.",
        ],
        "safety_note": None,
    },
]

# ---------------------------------------------------------------------------
# THE DAO PATH — Year 1: Foundation (Zhu Ji)
# ---------------------------------------------------------------------------

STAGES = [
    {
        "stage_id": "y1s1",
        "order": 1,
        "year": 1,
        "months": "Months 1\u20133",
        "title": "Body Opening",
        "chinese": "\u7b51\u57fa",
        "subtitle": "Loosen the body, awaken circulation",
        "description": "The journey begins not with energy work but with the body itself. Before qi can move freely, the joints, muscles and fascia must open. These three months are about gentle, daily movement — Daoyin stretching, the Eight Brocades, and the playful Five Animal Frolics.",
        "practices": ["daoyin", "ba-duan-jin", "wu-qin-xi"],
        "daily_guidance": "Begin each day with 15\u201320 minutes of Daoyin stretching. Add Ba Duan Jin three mornings a week, and let the Five Animal Frolics be your playful practice on the others.",
        "timeline_expectation": "Expect looser joints and easier movement within a few weeks. Deeper changes are quiet and slow.",
        "honest_note": "You may feel nothing but slightly looser joints for weeks \u2014 that is exactly right. The body opens long before any energy moves.",
        "recommended_days": 90,
        "min_checkins": 3,
    },
    {
        "stage_id": "y1s2",
        "order": 2,
        "year": 1,
        "months": "Months 4\u20136",
        "title": "Breathwork",
        "chinese": "\u5410\u7d0d",
        "subtitle": "Return the breath to its natural depth",
        "description": "With the body opening, attention turns to the breath. You begin with natural breathing, sink it into the lower belly, and are gradually introduced to the Long Breath Method \u2014 moving from ten-minute sessions toward twenty.",
        "practices": ["shun-hu-xi", "abdominal-breathing", "long-breath"],
        "daily_guidance": "Practise 10\u201320 minutes of breathing daily. Start with natural breathing, settle into abdominal breathing, and only lengthen the breath once it feels easy.",
        "timeline_expectation": "Sessions grow from 10 to 20 minutes over the three months. Let length arrive naturally.",
        "honest_note": "The breath will feel forced before it feels natural. Do not chase length \u2014 chase ease.",
        "recommended_days": 90,
        "min_checkins": 3,
    },
    {
        "stage_id": "y1s3",
        "order": 3,
        "year": 1,
        "months": "Months 7\u20139",
        "title": "Standing & Seated",
        "chinese": "\u7ad9\u6841",
        "subtitle": "Build structural stillness",
        "description": "Now stillness enters the practice. Zhan Zhuang (standing meditation) builds structural alignment and rooted patience, while seated Jinggong trains the mind toward quiet. Both are simple to describe and demanding to do.",
        "practices": ["zhan-zhuang", "jinggong"],
        "daily_guidance": "Stand in Zhan Zhuang for a few minutes daily, growing slowly. Follow it with seated stillness, resting attention on the breath.",
        "timeline_expectation": "Standing time grows gradually. Shaking legs and a wandering mind are part of the work, not signs of failure.",
        "honest_note": "Your legs will shake and your mind will wander. Both are the practice, not obstacles to it.",
        "recommended_days": 90,
        "min_checkins": 3,
    },
    {
        "stage_id": "y1s4",
        "order": 4,
        "year": 1,
        "months": "Months 10\u201312",
        "title": "Yangsheng \u2014 Life Nourishing",
        "chinese": "\u990a\u751f",
        "subtitle": "Weave practice into daily living",
        "description": "The final stage of Year 1 gathers everything into daily life. Daoist dietary principles, sleep rhythm, seasonal living and the conservation of Jing turn practice from something you 'do' into the quiet shape of an ordinary day.",
        "practices": ["yangsheng-diet", "sleep-hygiene", "seasonal-living", "jing-conservation"],
        "daily_guidance": "Keep your movement and breath practice, and begin folding in one yangsheng principle at a time \u2014 warmer food, earlier sleep, seasonal rhythm.",
        "timeline_expectation": "This stage is less about sessions and more about slow reorganisation of daily habits.",
        "honest_note": "Nourishing life is not another task on the list. It is the quiet reorganising of the ordinary day.",
        "recommended_days": 90,
        "min_checkins": 3,
    },
]

# Prompt template for AI ink-wash illustration generation per practice.
ILLUSTRATION_STYLE = (
    "Traditional Chinese/East-Asian sumi-e ink wash painting, minimalist, "
    "soft muted earth tones on warm off-white rice-paper texture, sage green and "
    "sepia accents, generous negative space, calm and meditative, no text, no words, "
    "no letters, subtle brush strokes. Subject: "
)

PRACTICE_ILLUSTRATION_SUBJECT = {
    "daoyin": "a single serene figure gently stretching and reaching, flowing robes",
    "ba-duan-jin": "a calm figure with both arms raised overhead holding up the sky",
    "wu-qin-xi": "graceful silhouettes suggesting a crane and a tiger in motion",
    "shun-hu-xi": "a seated figure in quiet meditation, faint mist of breath",
    "abdominal-breathing": "a seated figure with one hand resting on the lower belly, soft ripples",
    "long-breath": "a lone figure by still water with a long thin trail of mist",
    "zhan-zhuang": "a figure standing rooted like a post, arms rounded holding a ball of air",
    "jinggong": "a figure in seated meditation beneath a single bending pine",
    "yangsheng-diet": "a simple bowl of warm food and a teacup on a low table",
    "sleep-hygiene": "a crescent moon over distant mountains, deep restful night",
    "seasonal-living": "four small branches showing the turning of the four seasons",
    "jing-conservation": "a still lantern flame sheltered from the wind",
    "dinacharya": "sunrise over calm hills with a small figure beginning the day",
    "tongue-scraping": "a minimalist morning still life with a copper tool and bowl",
    "abhyanga": "a small bottle of oil and warm cloth, soft self-care stillness",
    "nadi-shodhana": "a seated figure with one hand near the nose, balanced breath channels",
    "ujjayi": "gentle ocean waves suggested by a few soft brush strokes",
    "dosha-awareness": "three simple abstract elements: air, fire and earth in balance",
    "ritucharya": "seasonal fruits and grains arranged simply on rice paper",
    "warm-water": "steam rising gently from a simple cup of warm water",
}
