#!/usr/bin/env node
// Copies docs/terms-of-service.md and docs/privacy-policy.md into the app, so
// the in-app pages and the web pages (/legal/terms, /legal/privacy) always
// match the documents in the repo. Run after editing either document:
//   node scripts/build-legal.js
const fs = require("fs");
const path = require("path");

const docs = path.resolve(__dirname, "../../docs");
const out = path.resolve(__dirname, "../src/legal/generated.ts");
const read = (f) => fs.readFileSync(path.join(docs, f), "utf8");

const body =
  "// Generated by scripts/build-legal.js from docs/. Do not edit by hand.\n" +
  `export const TERMS = ${JSON.stringify(read("terms-of-service.md"))};\n` +
  `export const PRIVACY = ${JSON.stringify(read("privacy-policy.md"))};\n`;
fs.writeFileSync(out, body);
console.log("wrote", path.relative(process.cwd(), out));
